version: '3'

services:
  nodeworker:
    image: abhishek1857/blockdag:preawakening-v0.0.1
    container_name: blockdag-testnet-network
    restart: unless-stopped
    ports:
      - "38131:38131"
      - "18545:18545"
      - "18546:18546"
      - "18150:18150"
    volumes:
      - bdag_bin:/opt/bdag
      - ./bin/bdag/data:/bdag/data
      - ./bin/bdag/logs:/bdag/logs
    environment:
      NODE_ARGS: '--rpclisten=0.0.0.0:38131 --notls --rpcuser=test --rpcpass=test --generate --miner --miningaddr=${MINING_ADDRESS} --walletpass=test --evmenv="--http --http.port=18545 --http.addr=0.0.0.0 --http.api=net,web3,debug,eth,bdag,txpool,trace,erigon --ws --ws.origins=* --ws.addr=0.0.0.0 --ws.port=18546 --http.corsdomain=* --http.vhosts=* --http.corsdomain=*" --miningstatesync --rpcmaxclients=500 --addpeer=/ip4/44.246.2.144/tcp/18150/p2p/16Uiu2HAkyoRzku3nYRHjuFBrqxWcYHex5uj4WjkaNHdGEYWqaJCw'
      RPC_URL: ws://127.0.0.1:18546
      CONTRACT_ADDRESS: 0x2000000000000000000000000000000000000000

volumes:
  bdag_bin: {}
