version: '3'

services:
  bdag:
    image: blockdagnetwork/primordial:v1.0.1
    container_name: blockdag-testnet-network
    ports:
      - "38131:38131"
      - "18545:18545"
      - "18546:18546"
      - "18150:18150"
    volumes:
      - ./bin/bdag/data:/bdag/data
      - ./bin/bdag/logs:/bdag/logs
    command: >
      ./bdag
      --testnet
      --rpclisten=0.0.0.0:38131
      --notls
      --rpcuser=test
      --rpcpass=test
      --miner
      --miningaddr=${MINING_ADDRESS}
      --generate
      --walletpass=test
      --evmenv="--http --http.port=18545 --http.addr=0.0.0.0 --http.api=net,web3,eth,bdag --ws --ws.origins=* --ws.port=18546 --ws.addr=0.0.0.0 --http.corsdomain=* --http.vhosts=* --http.corsdomain=*"
      --miningstatesync
      --addpeer=/ip4/44.246.2.144/tcp/18150/p2p/16Uiu2HAkyoRzku3nYRHjuFBrqxWcYHex5uj4WjkaNHdGEYWqaJCw
